"""Create a baseline migrations

Revision ID: 4a77d0e6f363
Revises: 
Create Date: 2024-02-04 03:12:19.376477

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a77d0e6f363"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("access_token_encrypted", sa.String(), nullable=True),
        sa.Column("refresh_token_encrypted", sa.String(), nullable=True),
        sa.Column("feed_token_encrypted", sa.String(), nullable=True),
        sa.Column("broker_account_id", sa.String(), nullable=False),
        sa.Column("access_token_expires", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("broker_account_id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)

    op.create_table(
        "tokens",
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("symbol", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("expiry_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("strike", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("lotsize", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("instrumenttype", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("exch_seg", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("tick_size", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("token", "id", name="tokens_pkey"),
        sa.UniqueConstraint("token", name="tokens_token_key"),
    )
    op.create_index("ix_tokens_symbol", "tokens", ["symbol"], unique=False)
    op.create_index("ix_tokens_id", "tokens", ["id"], unique=False)
    op.create_index("ix_tokens_expiry_date", "tokens", ["expiry_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("tokens")
    op.drop_index("ix_tokens_expiry_date", table_name="tokens")
    op.drop_index("ix_tokens_id", table_name="tokens")
    op.drop_index("ix_tokens_symbol", table_name="tokens")
    # ### end Alembic commands ###
